//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Borrador estructura de datos.rc
//
#define IDD_DIALOG1                     101
#define IDD_DIALOG2                     103
#define IDR_MENU1                       105
#define IDD_DIALOG3                     106
#define IDD_DIALOG4                     108
#define IDD_DIALOG5                     110
#define IDD_DIALOG6                     112
#define IDD_DIALOG7                     114
#define IDD_DIALOG8                     116
#define IDD_DIALOG9                     118
#define IDD_DIALOG10                    120
#define IDD_DIALOG11                    122
#define IDD_DIALOG12                    123
#define IDD_DIALOG13                    126
#define IDD_DIALOG14                    127
#define IDD_DIALOG15                    134
#define nameuser                        1001
#define contra                          1002
#define iniciarsesion                   1003
#define regis                           1004
#define nameu                           1005
#define ap                              1006
#define am                              1007
#define contras                         1008
#define G_RU                            1009
#define R_RU                            1010
#define tv                              1011
#define contras2                        1011
#define m                               1012
#define IDC_COMBO1                      1013
#define cv                              1014
#define d                               1015
#define ninero                          1016
#define G_VA                            1017
#define R_VA                            1018
#define np                              1019
#define app                             1020
#define ampersona                       1021
#define curpi                           1022
#define fnp                             1023
#define dp                              1024
#define gene                            1025
#define telp                            1026
#define ine                             1027
#define G_RP                            1028
#define work                            1029
#define R_RP                            1030
#define ec                              1031
#define C_Vacunas                       1032
#define C_NumDosis                      1033
#define datee                           1034
#define centro                          1035
#define C_Personas                      1036
#define G_RC                            1037
#define R_RC                            1038
#define datee2                          1039
#define nombreuser                      1040
#define nombreuser2                     1041
#define nombreuser3                     1042
#define nombreuser4                     1043
#define nombreuser5                     1044
#define IDC_LIST1                       1045
#define ListadoEDI                      1046
#define ListadoREG                      1047
#define ListadoELI                      1048
#define IUN                             1049
#define IUAP                            1050
#define ncomu2                          1051
#define IUAM                            1052
#define IUAP2                           1053
#define IUC                             1054
#define IUAM2                           1055
#define IUCL                            1056
#define IUC2                            1057
#define ncomu                           1058
#define IUCL2                           1059
#define IUN2                            1060
#define ListadoREGV                     1061
#define B_ACTU                          1062
#define B_CU                            1063
#define IDC_LIST2                       1064
#define ncomu3                          1065
#define IV_TV                           1066
#define IV_M                            1067
#define IV_CV                           1068
#define IV_D                            1069
#define IV_NINERO                       1070
#define ListadoELIV                     1071
#define ListadoEDIV                     1072
#define IV_ND                           1073
#define ncomu4                          1074
#define IV_TV2                          1075
#define IV_M2                           1076
#define IV_CV2                          1077
#define IV_D2                           1078
#define IV_NINERO2                      1079
#define IDC_COMBO2                      1080
#define B_ACTV                          1081
#define B_CV                            1082
#define IP_EC                           1083
#define IP_G                            1084
#define ncomu5                          1085
#define IP_N                            1086
#define IP_AP                           1087
#define IP_AM                           1088
#define IP_C                            1089
#define IP_F                            1090
#define IP_D                            1091
#define IP_T                            1092
#define IP_DOC                          1093
#define IP_GO                           1094
#define ListadoELIP                     1095
#define ListadoEDIP                     1096
#define ListadoREGP                     1097
#define IDC_LIST3                       1098
#define ncomu6                          1099
#define IP_N2                           1100
#define IP_AP2                          1101
#define IP_AM2                          1102
#define IP_C2                           1103
#define IP_F2                           1104
#define IP_D2                           1105
#define IP_EC2                          1106
#define IP_T2                           1107
#define IP_DOC2                         1108
#define IP_G2                           1109
#define IP_GO2                          1110
#define B_ACTP                          1111
#define B_CP                            1112
#define IDC_RADIO1                      1113
#define IDC_RADIO2                      1114
#define ncomu7                          1115
#define IC_C                            1116
#define IC_U                            1117
#define IC_ND                           1118
#define IC_L                            1119
#define IC_F                            1120
#define INGRESAFOTO1                    1121
#define IC_CDA                          1122
#define FOTO1                           1123
#define ListadoELIC                     1124
#define INGRESAFOTO2                    1125
#define ListadoEDIC                     1126
#define FOTO2                           1127
#define ListadoREGC                     1128
#define FOTOP1                          1129
#define IDC_LIST4                       1130
#define IP_N4                           1131
#define ncomu8                          1132
#define IP_AP4                          1133
#define IC_C2                           1134
#define IP_AM4                          1135
#define IDC_BUTTON1                     1136
#define boton_reporte                   1137
#define IC_U2                           1138
#define Name_R                          1139
#define IP_C4                           1140
#define Doc_R                           1141
#define IC_ND2                          1142
#define Tel_R                           1143
#define IDC_EDIT1                       1143
#define reg_fum                         1144
#define IP_F4                           1145
#define Dire_R                          1146
#define IC_L2                           1147
#define Fecha_R                         1148
#define IP_D4                           1149
#define Genero_R                        1150
#define IC_F2                           1151
#define Work_R                          1152
#define IP_EC4                          1153
#define IC_CDA2                         1154
#define IP_T4                           1155
#define B_ACTC                          1156
#define IP_DOC4                         1157
#define B_CC                            1158
#define IP_G4                           1159
#define IP_GO4                          1160
#define FOTOP14                         1161
#define ID_USUARIO_REGISTRODEUSUARIO    40001
#define ID_USUARIO_LISTADODEUSUARIO     40002
#define ID_USUARIO_EDICIONDEUSUARIO     40003
#define ID_USUARIO_BAJADEUSUARIO        40004
#define ID_VACUNA_REGISTRODEVACUNA      40005
#define ID_VACUNA_LISTADODEVACUNA       40006
#define ID_VACUNA_EDICIONDEVACUNA       40007
#define ID_VACUNA_BAJADEVACUNA          40008
#define ID_PERSONA_REGISTRODEPERSONA    40009
#define ID_PERSONA_LISTADODEPERSONA     40010
#define ID_PERSONA_EDICIONDEPERSONA     40011
#define ID_PERSONA_BAJADEPERSONA        40012
#define ID_CARNET_REGISTRODECARNETDEVACUNACION 40013
#define ID_CARNET_LISTADODECARNETDEVACUNACION 40014
#define ID_CARNET_EDICIONDECARNETDEVACUNACION 40015
#define ID_CARNET_BAJADECA              40016
#define ID_SALIR_SALIR40018             40017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         1145
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
